name: "She's had good eats"
favicon: null
layout_spectrum: 0.12760710390284657
typography_spectrum: 0.5735086700879037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.26871644519269466
  lightness: 0.9499643223825842
  saturation: 0.6935484895948321
  rhythmicContrast: 0.8322662222199142
purpose: []
